base_config: ../spinexnet.yaml
experiment_name: ablation_biomedclip_concepts_only

data:
  concept_columns:
    - concept_biomedclip_disc_height_loss
    - concept_biomedclip_disc_signal_loss
    - concept_biomedclip_endplate_change
    - concept_biomedclip_osteophyte_formation
    - concept_biomedclip_facet_hypertrophy
    - concept_biomedclip_ligamentum_flavum_thickening
    - concept_biomedclip_spinal_canal_narrowing
    - concept_biomedclip_neural_foraminal_narrowing
    - concept_biomedclip_disc_bulge_or_herniation
    - concept_biomedclip_abnormal_vertebral_alignment

model:
  num_concepts: 10

